export const RELIC_UPGRADES = [
  {
    id: "relics:venom_ward",
    displayName: "Venom Ward",
    slot: "face",
    inputs: ["relics:filter_mask", "relics:blight_vessel"],
    custom: "full_toxin_ward",
  },
  {
    id: "relics:nimbus_mantle",
    displayName: "Nimbus Mantle",
    slot: "back",
    inputs: ["relics:cloud_cape", "relics:cloud_vial"],
    custom: "triple_jump",
  },
  {
    id: "relics:inferno_brand",
    displayName: "Inferno Brand",
    slot: "necklace",
    inputs: ["relics:ember_locket", "relics:cinderfist"],
    onAttack: { ignite: { chance: 1, seconds: 8 } },
  },
  {
    id: "relics:veinheart_gauntlets",
    displayName: "Veinheart Gauntlets",
    slot: "hands",
    inputs: ["relics:haste_band", "relics:excavator_gauntlets"],
    passive: { effect: "haste", amplifier: 2 },
    custom: "double_ore",
    oreChance: 0.55,
  },
  {
    id: "relics:vital_bloom",
    displayName: "Vital Bloom",
    slot: "ring",
    inputs: ["relics:bloom_band", "relics:vital_band"],
    passive: { effect: "regeneration", amplifier: 1 },
    custom: "second_wind",
    secondWindHp: 12,
    secondWindDuration: 260,
    secondWindAmplifier: 3,
    secondWindCooldown: 500,
  },
  {
    id: "relics:alchemists_focus",
    displayName: "Alchemist's Focus",
    slot: "ring",
    inputs: ["relics:purifying_flask", "relics:draught_band"],
    custom: "grand_alchemy",
    potionBonus: 0.5,
  },
  {
    id: "relics:tempest_choker",
    displayName: "Tempest Choker",
    slot: "necklace",
    inputs: ["relics:storm_locket", "relics:marrow_choker"],
    onAttack: { lightning: { chance: 1 }, wither: { duration: 120, amplifier: 1 } },
  },
  {
    id: "relics:gale_aegis",
    displayName: "Gale Aegis",
    slot: "back",
    inputs: ["relics:stratos_pack", "relics:skybound_charm"],
    custom: "gale_glide",
    passive: { effect: "slow_falling", amplifier: 0 },
  },
  {
    id: "relics:bulwark_plate",
    displayName: "Bulwark Plate",
    slot: "body",
    inputs: ["relics:obsidian_plate", "relics:cinder_ward"],
    passive: { effect: "resistance", amplifier: 1 },
    onHurt: { effect: "strength", amplifier: 2, duration: 140 },
    custom: "fire_res_on_burn",
  },
  {
    id: "relics:treasure_lure",
    displayName: "Treasure Lure",
    slot: "belt",
    inputs: ["relics:gilt_hook", "relics:magnetic_sash"],
    passive: { effect: "luck", amplifier: 3 },
    custom: "fishing_haul",
    magnetRadius: 14,
  },
  {
    id: "relics:soothsayers_reap",
    displayName: "Soothsayer's Reap",
    slot: "head",
    inputs: ["relics:fortune_tellers_cap", "relics:reapers_hook"],
    onKill: { bonusXpOrbs: 12 },
  },
  {
    id: "relics:executioners_phantom",
    displayName: "Executioner's Phantom",
    slot: "charm",
    inputs: ["relics:lucky_talisman", "relics:shrink_charm"],
    custom: "executioners_phantom",
    dodgeChance: 0.24,
    executeThreshold: 0.35,
    executeBonus: 5,
  },
  {
    id: "relics:leviathan_striders",
    displayName: "Leviathan Striders",
    slot: "feet",
    inputs: ["relics:tidewalkers", "relics:finfoot_boots"],
    custom: "leviathan_striders",
  },
  {
    id: "relics:sanguine_heartguard",
    displayName: "Sanguine Heartguard",
    slot: "necklace",
    inputs: ["relics:heartstone", "relics:ward_pendant"],
    passive: { effect: "health_boost", amplifier: 2 },
    onHurt: { effect: "resistance", amplifier: 1, duration: 100 },
  },
  {
    id: "relics:warhammer_fist",
    displayName: "Warhammer Fist",
    slot: "hands",
    inputs: ["relics:crusher_gauntlet", "relics:impact_knuckles"],
    onAttack: { bonusDamage: 4, knockback: 1.6 },
  },
  {
    id: "relics:crimson_wargrip",
    displayName: "Crimson Wargrip",
    slot: "hands",
    inputs: ["relics:fleetstrike_gloves", "relics:leeching_glove"],
    passive: { effect: "strength", amplifier: 1 },
    onAttack: { lifesteal: 0.22 },
  },
  {
    id: "relics:nightseers_gaze",
    displayName: "Nightseer's Gaze",
    slot: "face",
    inputs: ["relics:scryglass", "relics:lumen_visor"],
    passive: { effect: "night_vision", amplifier: 0 },
    custom: "reveal_hostiles",
    revealRadius: 24,
  },
  {
    id: "relics:thornroot_ward",
    displayName: "Thornroot Ward",
    slot: "feet",
    inputs: ["relics:bramble_charm", "relics:rootgrip_boots"],
    custom: "knockback_resist",
    onHurt: { thorns: { chance: 0.5, damage: 4 } },
  },
  {
    id: "relics:windsprint_greaves",
    displayName: "Windsprint Greaves",
    slot: "feet",
    inputs: ["relics:springheel_boots", "relics:marathoners_treads"],
    passive: { effect: "speed", amplifier: 2 },
    custom: "windsprint_greaves",
  },
  {
    id: "relics:abyssal_gillchain",
    displayName: "Abyssal Gillchain",
    slot: "necklace",
    inputs: ["relics:anchor_charm", "relics:gillmask"],
    passive: { effect: "water_breathing", amplifier: 0 },
    custom: "fluid_movement",
  },
];

const UPGRADE_BY_ID = new Map(RELIC_UPGRADES.map((u) => [u.id, u]));

export function getUpgradeDef(id) {
  return UPGRADE_BY_ID.get(id);
}

export function isUpgradeRelic(id) {
  return UPGRADE_BY_ID.has(id);
}
